version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: lmovies_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: user
    #   MONGO_INITDB_ROOT_PASSWORD: password

  backend:
    build: ./backend
    container_name: lmovies_backend
    command: sh -c "python manage.py makemigrations && python manage.py migrate && gunicorn --bind 0.0.0.0:8000 core.wsgi:application"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://db:27017
      - DEBUG=False

  frontend:
    build: ./frontend
    container_name: lmovies_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo_data:
